### ISSUE TITLE
Should we keep citekit in the the sparql environment or should it come with the plugin?

### ISSUE THREAD

**Issue by SamuelHill** [wcatron/SPARQL-Environment#35]
This would just help clean up the js folder. While we are at it we might as well delete the tokenizer.js because nothing is using it and the botcar-apps repo has a copy.

**Comment by wcatron** [comment]
CiteKit and GraphKit should be moved out of the default installation of spraql environment but should pulled in during the URN resolution of the plugins that are dependent on them. Plugins need some kind of dependency system. Or perhaps dependancies are plugins themselves they just don't have a visual presents.
